"""Add WorkspaceInvitation
Revision ID: 42b143738072
Revises: 002_crm_module
Create Date: 2026-06-19 19:43:04.830190
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
revision: str = '42b143738072'
down_revision: Union[str, None] = '002_crm_module'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_invitations',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'COMPANY_ADMIN', 'SALES_REPRESENTATIVE', 'AMBASSADOR', name='userrole'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_invitations_code'), 'workspace_invitations', ['code'], unique=True)
    op.create_table('erp_invoices',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PAID', 'OVERDUE', name='erpinvoicestatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'invoice_number')
    )
    op.create_index(op.f('ix_erp_invoices_company_id'), 'erp_invoices', ['company_id'], unique=False)
    op.create_index(op.f('ix_erp_invoices_customer_id'), 'erp_invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_erp_invoices_deal_id'), 'erp_invoices', ['deal_id'], unique=False)
    op.create_table('erp_invoice_items',
    sa.Column('erp_invoice_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['erp_invoice_id'], ['erp_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_invoice_items_erp_invoice_id'), 'erp_invoice_items', ['erp_invoice_id'], unique=False)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_erp_invoice_items_erp_invoice_id'), table_name='erp_invoice_items')
    op.drop_table('erp_invoice_items')
    op.drop_index(op.f('ix_erp_invoices_deal_id'), table_name='erp_invoices')
    op.drop_index(op.f('ix_erp_invoices_customer_id'), table_name='erp_invoices')
    op.drop_index(op.f('ix_erp_invoices_company_id'), table_name='erp_invoices')
    op.drop_table('erp_invoices')
    op.drop_index(op.f('ix_workspace_invitations_code'), table_name='workspace_invitations')
    op.drop_table('workspace_invitations')
    # ### end Alembic commands ###