"""add_pipeline_stages

Revision ID: ca68288c4d46
Revises: e61aadb246ba
Create Date: 2026-06-19 21:22:11.506798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ca68288c4d46'
down_revision: Union[str, None] = 'e61aadb246ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_stages',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_stages_company_id'), 'pipeline_stages', ['company_id'], unique=False)
    op.add_column('leads', sa.Column('custom_stage_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_leads_custom_stage_id'), 'leads', ['custom_stage_id'], unique=False)
    with op.batch_alter_table('leads') as batch_op:
        batch_op.create_foreign_key('fk_leads_custom_stage_id', 'pipeline_stages', ['custom_stage_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads') as batch_op:
        batch_op.drop_constraint('fk_leads_custom_stage_id', type_='foreignkey')
    op.drop_index(op.f('ix_leads_custom_stage_id'), table_name='leads')
    op.drop_column('leads', 'custom_stage_id')
    op.drop_index(op.f('ix_pipeline_stages_company_id'), table_name='pipeline_stages')
    op.drop_table('pipeline_stages')
    # ### end Alembic commands ###
